# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Additional_Constraints.xdc

# Block Designs: bd/IPCreation/IPCreation.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IPCreation || ORIG_REF_NAME==IPCreation} -quiet] -quiet

# IP: bd/IPCreation/ip/IPCreation_processing_system7_0_0/IPCreation_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IPCreation_processing_system7_0_0 || ORIG_REF_NAME==IPCreation_processing_system7_0_0} -quiet] -quiet

# IP: bd/IPCreation/ip/IPCreation_MyGPIO_0_1/IPCreation_MyGPIO_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IPCreation_MyGPIO_0_1 || ORIG_REF_NAME==IPCreation_MyGPIO_0_1} -quiet] -quiet

# IP: bd/IPCreation/ip/IPCreation_ps7_0_axi_periph_1/IPCreation_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IPCreation_ps7_0_axi_periph_1 || ORIG_REF_NAME==IPCreation_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/IPCreation/ip/IPCreation_rst_ps7_0_100M_1/IPCreation_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IPCreation_rst_ps7_0_100M_1 || ORIG_REF_NAME==IPCreation_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/IPCreation/ip/IPCreation_auto_pc_0/IPCreation_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IPCreation_auto_pc_0 || ORIG_REF_NAME==IPCreation_auto_pc_0} -quiet] -quiet

# XDC: bd/IPCreation/ip/IPCreation_processing_system7_0_0/IPCreation_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==IPCreation_processing_system7_0_0 || ORIG_REF_NAME==IPCreation_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/IPCreation/ip/IPCreation_rst_ps7_0_100M_1/IPCreation_rst_ps7_0_100M_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==IPCreation_rst_ps7_0_100M_1 || ORIG_REF_NAME==IPCreation_rst_ps7_0_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/IPCreation/ip/IPCreation_rst_ps7_0_100M_1/IPCreation_rst_ps7_0_100M_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==IPCreation_rst_ps7_0_100M_1 || ORIG_REF_NAME==IPCreation_rst_ps7_0_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/IPCreation/ip/IPCreation_auto_pc_0/IPCreation_auto_pc_0_ooc.xdc

# XDC: bd/IPCreation/IPCreation_ooc.xdc
