# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Y4/hardsoft/Lab/project_1_interrupt/project_1_interrupt.srcs/sources_1/bd/ZyboIPCreation/ip/ZyboIPCreation_processing_system7_0_1/ZyboIPCreation_processing_system7_0_1.xci
# IP: The module: 'ZyboIPCreation_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Y4/hardsoft/Lab/project_1_interrupt/project_1_interrupt.srcs/sources_1/bd/ZyboIPCreation/ip/ZyboIPCreation_processing_system7_0_1/ZyboIPCreation_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZyboIPCreation_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Y4/hardsoft/Lab/project_1_interrupt/project_1_interrupt.srcs/sources_1/bd/ZyboIPCreation/ip/ZyboIPCreation_processing_system7_0_1/ZyboIPCreation_processing_system7_0_1.xci
# IP: The module: 'ZyboIPCreation_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Y4/hardsoft/Lab/project_1_interrupt/project_1_interrupt.srcs/sources_1/bd/ZyboIPCreation/ip/ZyboIPCreation_processing_system7_0_1/ZyboIPCreation_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZyboIPCreation_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
